//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urun_kayıt_sistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int UrunId { get; set; }
        public string UrunAdi { get; set; }
        public string UrunKodu { get; set; }
        public string UrunUrl { get; set; }
        public Nullable<int> Urunfiyat { get; set; }
    }
}
